# Generated by Django 4.2.6 on 2023-10-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='published_year',
            field=models.DateTimeField(),
        ),
    ]
